### ISSUE TITLE
datashader is down due to nginx error, causing CircleCI to fail

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-sample-apps#531]
# App name

# Description of bug

# How to replicate the bug

# Other notes

**Comment by joaoalf** [comment]
* `hi-app` build error:

```
root@edb91ac1bad2:/app# dokku ps:rebuild hi-plot
-----> DDS disk space information
Filesystem      Size  Used Avail Use% Mounted on
overlay         2.0T  684G  1.3T  35% /
/dev/sdc        206G   86G  111G  44% /data
-----> DASH_APP_NAME => hi-plot
-----> DASH_DOMAIN_BASE => dash-gallery.plotly.host
-----> DASH_PATH_ROUTING => 1
-----> DASH_STREAMBED_DIRECT_IP => 172.17.0.1
-----> DASH_LOGOUT_URL => /Manager/api/logout
-----> SCRIPT_NAME => /hi-plot
-----> Cleaning up...
-----> Building hi-plot from herokuish...
rehash: warning: skipping ca-certificates.pem,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

updates of cacerts keystore disabled.
done.
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> Installing python-3.6.10
-----> Installing pip
-----> Installing requirements with pip
       Collecting https://dash-nightly.plotly.host/workshop/assets/dash_design_kit-1.4.0rc2.tar.gz (from -r /tmp/build/requirements.txt (line 1))
       Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba9dd30>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)')': /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz
       Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba9dbe0>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)')': /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz
       Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba9d940>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)')': /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz
       Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba9dda0>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)')': /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz
       Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba28a20>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)')': /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz
       Exception:
       Traceback (most recent call last):
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connection.py", line 141, in _new_conn
       (self.host, self.port), self.timeout, **extra_kw)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/util/connection.py", line 83, in create_connection
       raise err
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/util/connection.py", line 73, in create_connection
       sock.connect(sa)
       socket.timeout: timed out

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 601, in urlopen
       chunked=chunked)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 346, in _make_request
       self._validate_conn(conn)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 850, in _validate_conn
       conn.connect()
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connection.py", line 284, in connect
       conn = self._new_conn()
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connection.py", line 146, in _new_conn
       (self.host, self.timeout))
       pip._vendor.urllib3.exceptions.ConnectTimeoutError: (<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba28be0>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)')

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 440, in send
       timeout=timeout
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
       **response_kw)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
       **response_kw)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
       **response_kw)
       [Previous line repeated 2 more times]
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 639, in urlopen
       _stacktrace=sys.exc_info()[2])
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/urllib3/util/retry.py", line 388, in increment
       raise MaxRetryError(_pool, url, error or ResponseError(cause))
       pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dash-nightly.plotly.host', port=443): Max retries exceeded with url: /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba28be0>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)'))

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
       status = self.run(options, args)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
       requirement_set.prepare_files(finder)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
       ignore_dependencies=self.ignore_dependencies))
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
       session=self.session, hashes=hashes)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
       hashes=hashes
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
       hashes)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
       stream=True,
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
       return self.request('GET', url, **kwargs)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/download.py", line 386, in request
       return super(PipSession, self).request(method, url, *args, **kwargs)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
       resp = self.send(prep, **send_kwargs)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
       r = adapter.send(request, **kwargs)
       File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 496, in send
       raise ConnectTimeout(e, request=request)
       pip._vendor.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='dash-nightly.plotly.host', port=443): Max retries exceeded with url: /workshop/assets/dash_design_kit-1.4.0rc2.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad9ba28be0>, 'Connection to dash-nightly.plotly.host timed out. (connect timeout=15)'))
```

* `dash-datashader` build error:
```
root@edb91ac1bad2:/app# dokku ps:rebuild dash-datashader
-----> DDS disk space information
Filesystem      Size  Used Avail Use% Mounted on
overlay         2.0T  685G  1.3T  35% /
/dev/sdc        206G   86G  111G  44% /data
-----> DASH_APP_NAME => dash-datashader
-----> DASH_DOMAIN_BASE => dash-gallery.plotly.host
-----> DASH_PATH_ROUTING => 1
-----> DASH_STREAMBED_DIRECT_IP => 172.17.0.1
-----> DASH_LOGOUT_URL => /Manager/api/logout
-----> SCRIPT_NAME => /dash-datashader
-----> Cleaning up...
-----> Building dash-datashader from herokuish...
rehash: warning: skipping ca-certificates.pem,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

updates of cacerts keystore disabled.
done.
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> Installing python-3.6.2
-----> Installing pip
-----> Installing requirements with pip
       Collecting cloudpickle>=1.1.1 (from -r /tmp/build/requirements.txt (line 1))
       Downloading https://files.pythonhosted.org/packages/e7/e3/898487e5dbeb612054cf2e0c188463acb358167fef749c53c8bb8918cea1/cloudpickle-1.6.0-py3-none-any.whl
       Collecting dash>=1.0.0 (from -r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/69/91/ae029886dda55b93b60ac04377bcb2ab9209dd73244e3b5e513124cc6778/dash-1.17.0.tar.gz (75kB)
       Collecting dask>=0.17.1 (from -r /tmp/build/requirements.txt (line 3))
       Downloading https://files.pythonhosted.org/packages/04/94/b4012c61c09300f4413c58a522a6cc1a212dc4a7f6fe1ba98d67429c089d/dask-2.30.0-py3-none-any.whl (848kB)
       Collecting datashader>=0.6.9 (from -r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/13/84/1af4ba0029068162088965ab16d4c288c9bf8052851512a0e68091bb0a02/datashader-0.11.1-py2.py3-none-any.whl (15.5MB)
       Collecting gunicorn>=19.9.0 (from -r /tmp/build/requirements.txt (line 5))
       Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
       Collecting numpy>=1.14.1 (from -r /tmp/build/requirements.txt (line 6))
       Downloading https://files.pythonhosted.org/packages/a6/fc/36e52d0ae2aa502b211f1bcd2fdeec72d343d58224eabcdddc1bcb052db1/numpy-1.19.4-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
       Collecting pandas>=0.24.0 (from -r /tmp/build/requirements.txt (line 7))
       Downloading https://files.pythonhosted.org/packages/4d/51/bafcff417cd857bc6684336320863b5e5af280530213ef8f534b6042cfe6/pandas-1.1.4-cp36-cp36m-manylinux1_x86_64.whl (9.5MB)
       Collecting fsspec>=0.3.3 (from -r /tmp/build/requirements.txt (line 8))
       Downloading https://files.pythonhosted.org/packages/a5/8b/1df260f860f17cb08698170153ef7db672c497c1840dcc8613ce26a8a005/fsspec-0.8.4-py3-none-any.whl (91kB)
       Collecting Flask>=1.0.2 (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
       Collecting flask-compress (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/b2/7a/9c4641f975fb9daaf945dc39da6a52fd5693ab3bbc2d53780eab3b5106f4/Flask_Compress-1.8.0-py3-none-any.whl
       Collecting plotly (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/4c/f3/93bc71d449828098efc7dda0a682937762d0c17f6140dcbc6fc6fa2a467d/plotly-4.13.0-py2.py3-none-any.whl (13.1MB)
       Collecting dash_renderer==1.8.3 (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/72/fe/59a322edb128ad15205002c7b81e3f5e580f6791c4a100183289e05dbfcb/dash_renderer-1.8.3.tar.gz (1.0MB)
       Collecting dash-core-components==1.13.0 (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/52/48/3dd8c7bf93cff3a9dd9d360bc25c4ec0cb191acdce13375c3ff85f98e992/dash_core_components-1.13.0.tar.gz (3.5MB)
       Collecting dash-html-components==1.1.1 (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/02/ba/bb9427c62feb25bfbaf243894eeeb4e7c67a92b426ed0575a167100e436e/dash_html_components-1.1.1.tar.gz (188kB)
       Collecting dash-table==4.11.0 (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/bb/46/cc839f897cabea3f584cf59ce9d86a5ea3828e54eefe2537ba8b640a9707/dash_table-4.11.0.tar.gz (1.8MB)
       Collecting future (from dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
       Collecting pyyaml (from dask>=0.17.1->-r /tmp/build/requirements.txt (line 3))
       Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
       Collecting numba!=0.49.*,!=0.50.*,>=0.37.0 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/5e/81/6fd1dd064bcf71a79da109e8966a39e2da61d68bf0bd1e0839fa997f8c41/numba-0.51.2.tar.gz (2.1MB)
       Collecting scipy (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9MB)
       Collecting colorcet>=0.9.0 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/b5/a4/8a5a364492af01c8b689987ce792d0d00835bbb1203a5cd5e49798a41fbd/colorcet-2.0.2-py2.py3-none-any.whl (1.6MB)
       Collecting pyct[cmd]==0.4.6 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/eb/76/cdf8ba7edc7be2a26d418ff8d1ff695a7ac024761bda1ad6f8e269a90434/pyct-0.4.6-py2.py3-none-any.whl
       Collecting xarray>=0.9.6 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/7a/cc/62ca520e349e63b05ce43c781757cbd3bea71d83ece96f2176763b57e8c2/xarray-0.16.1-py3-none-any.whl (720kB)
       Collecting toolz>=0.7.4 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/12/f5/537e55f8ba664ff2a26f26913010fb0fcb98b6bbadc6158af888184fd0b7/toolz-0.11.1-py3-none-any.whl (55kB)
       Collecting pillow>=3.1.1 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/5f/19/d4c25111d36163698396f93c363114cf1cddbacb24744f6612f25b6aa3d0/Pillow-8.0.1-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
       Collecting datashape>=0.5.1 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/a6/5b/95b2ed56b61e649b69c9a5b1ecb32ff0a5cd68b9f69f5aa7774540e6b444/datashape-0.5.2.tar.gz (76kB)
       Collecting param>=1.6.0 (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/d6/06/10ef78c8919449714d72bb9f808c920f3e67af7087da7b947f960f9704eb/param-1.10.0-py2.py3-none-any.whl (75kB)
       Collecting bokeh (from datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/88/20/f67d851da06f0f9358ae4e62296e76fefafaa1a5991f1c69496a83ee09ab/bokeh-2.2.3.tar.gz (8.8MB)
       Collecting python-dateutil>=2.7.3 (from pandas>=0.24.0->-r /tmp/build/requirements.txt (line 7))
       Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
       Collecting pytz>=2017.2 (from pandas>=0.24.0->-r /tmp/build/requirements.txt (line 7))
       Downloading https://files.pythonhosted.org/packages/12/f8/ff09af6ff61a3efaad5f61ba5facdf17e7722c4393f7d8a66674d2dbd29f/pytz-2020.4-py2.py3-none-any.whl (509kB)
       Collecting itsdangerous>=0.24 (from Flask>=1.0.2->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
       Collecting Werkzeug>=0.15 (from Flask>=1.0.2->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
       Collecting Jinja2>=2.10.1 (from Flask>=1.0.2->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
       Collecting click>=5.1 (from Flask>=1.0.2->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
       Collecting brotli (from flask-compress->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/b4/d3/7c98f05b7b9103e2f3a112ba42f269c798155b3e5404fb80bb8f823aaebe/Brotli-1.0.9-cp36-cp36m-manylinux1_x86_64.whl (357kB)
       Collecting retrying>=1.3.3 (from plotly->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
       Collecting six (from plotly->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
       Collecting llvmlite<0.35,>=0.34.0.dev0 (from numba!=0.49.*,!=0.50.*,>=0.37.0->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/0b/96/07bfa93a103fb9e3e9ae7f9f7c6687ae714aee66b6f3000da3fad71e0aa2/llvmlite-0.34.0.tar.gz (107kB)
       Collecting requests; extra == "cmd" (from pyct[cmd]==0.4.6->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl (61kB)
       Collecting multipledispatch>=0.4.7 (from datashape>=0.5.1->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/89/79/429ecef45fd5e4504f7474d4c3c3c4668c267be3370e4c2fd33e61506833/multipledispatch-0.6.0-py3-none-any.whl
       Collecting packaging>=16.8 (from bokeh->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
       Collecting tornado>=5.1 (from bokeh->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/01/d1/8750ad20cbcefb499bb8b405e243f83c2c89f78d139e6f8c8d800640f554/tornado-6.1-cp36-cp36m-manylinux1_x86_64.whl (427kB)
       Collecting typing_extensions>=3.7.4 (from bokeh->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
       Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->Flask>=1.0.2->dash>=1.0.0->-r /tmp/build/requirements.txt (line 2))
       Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
       Collecting certifi>=2017.4.17 (from requests; extra == "cmd"->pyct[cmd]==0.4.6->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/c1/6f/3d85f0850962279a7e4c622695d7b3171e95ac65308a57d3b29738b27149/certifi-2020.11.8-py2.py3-none-any.whl (155kB)
       Collecting urllib3<1.27,>=1.21.1 (from requests; extra == "cmd"->pyct[cmd]==0.4.6->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl (136kB)
       Collecting idna<3,>=2.5 (from requests; extra == "cmd"->pyct[cmd]==0.4.6->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
       Collecting chardet<4,>=3.0.2 (from requests; extra == "cmd"->pyct[cmd]==0.4.6->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
       Collecting pyparsing>=2.0.2 (from packaging>=16.8->bokeh->datashader>=0.6.9->-r /tmp/build/requirements.txt (line 4))
       Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
       Installing collected packages: cloudpickle, itsdangerous, Werkzeug, MarkupSafe, Jinja2, click, Flask, brotli, flask-compress, six, retrying, plotly, dash-renderer, dash-core-components, dash-html-components, dash-table, future, dash, pyyaml, dask, llvmlite, numpy, numba, scipy, param, certifi, urllib3, idna, chardet, requests, pyct, colorcet, python-dateutil, pytz, pandas, xarray, toolz, pillow, multipledispatch, datashape, pyparsing, packaging, tornado, typing-extensions, bokeh, datashader, gunicorn, fsspec
       Running setup.py install for retrying: started
       Running setup.py install for retrying: finished with status 'done'
       Running setup.py install for dash-renderer: started
       Running setup.py install for dash-renderer: finished with status 'done'
       Running setup.py install for dash-core-components: started
       Running setup.py install for dash-core-components: finished with status 'done'
       Running setup.py install for dash-html-components: started
       Running setup.py install for dash-html-components: finished with status 'done'
       Running setup.py install for dash-table: started
       Running setup.py install for dash-table: finished with status 'done'
       Running setup.py install for future: started
       Running setup.py install for future: finished with status 'done'
       Running setup.py install for dash: started
       Running setup.py install for dash: finished with status 'done'
       Running setup.py install for pyyaml: started
       Running setup.py install for pyyaml: finished with status 'done'
       Running setup.py install for llvmlite: started
       Running setup.py install for llvmlite: finished with status 'error'
       Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lw_qih1q/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7jb54ole-record/install-record.txt --single-version-externally-managed --compile:
       running install
       running build
       got version from file /tmp/pip-build-lw_qih1q/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
       running build_ext
       /app/.heroku/python/bin/python /tmp/pip-build-lw_qih1q/llvmlite/ffi/build.py
       LLVM version... Traceback (most recent call last):
       File "/tmp/pip-build-lw_qih1q/llvmlite/ffi/build.py", line 105, in main_posix
       out = subprocess.check_output([llvm_config, '--version'])
       File "/app/.heroku/python/lib/python3.6/subprocess.py", line 336, in check_output
       **kwargs).stdout
       File "/app/.heroku/python/lib/python3.6/subprocess.py", line 403, in run
       with Popen(*popenargs, **kwargs) as process:
       File "/app/.heroku/python/lib/python3.6/subprocess.py", line 707, in __init__
       restore_signals, start_new_session)
       File "/app/.heroku/python/lib/python3.6/subprocess.py", line 1333, in _execute_child
       raise child_exception_type(errno_num, err_msg)
       FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

       During handling of the above exception, another exception occurred:

       Traceback (most recent call last):
       File "/tmp/pip-build-lw_qih1q/llvmlite/ffi/build.py", line 191, in <module>
       main()
       File "/tmp/pip-build-lw_qih1q/llvmlite/ffi/build.py", line 181, in main
       main_posix('linux', '.so')
       File "/tmp/pip-build-lw_qih1q/llvmlite/ffi/build.py", line 108, in main_posix
       "to the path for llvm-config" % (llvm_config,))
       RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
       error: command '/app/.heroku/python/bin/python' failed with exit status 1

----------------------------------------
       Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lw_qih1q/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7jb54ole-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lw_qih1q/llvmlite/
```

**Comment by xhlulu** [comment]
I will delete both apps and try to restart `gallery`. Here's the info for datashader:
![image](https://user-images.githubusercontent.com/21180505/100377683-ad802100-2fdf-11eb-81da-e20250c49e11.png)

name: dash-datashader
title: Dash Datashader
description: View the app source code in Python (https://github.com/plotly/dash-sample-apps/tree/master/apps/dash-datashader).
rank: 20
tags: Time series,Datashader,Aerospace

**Comment by xhlulu** [comment]
Seems like redeploying the app in https://github.com/plotly/dash-sample-apps/pull/534 and fixing requirements in https://github.com/plotly/dash-sample-apps/pull/537 were not able to fix this datashader app; the following error still persists in the circle ci tests:

```
remote:        LLVM version... Traceback (most recent call last):        
remote:        File "/tmp/pip-build-5t5vcd8y/llvmlite/ffi/build.py", line 105, in main_posix        
remote:        out = subprocess.check_output([llvm_config, '--version'])        
remote:        File "/app/.heroku/python/lib/python3.7/subprocess.py", line 411, in check_output        
remote:        **kwargs).stdout        
remote:        File "/app/.heroku/python/lib/python3.7/subprocess.py", line 488, in run        
remote:        with Popen(*popenargs, **kwargs) as process:        
remote:        File "/app/.heroku/python/lib/python3.7/subprocess.py", line 800, in __init__        
remote:        restore_signals, start_new_session)        
remote:        File "/app/.heroku/python/lib/python3.7/subprocess.py", line 1551, in _execute_child        
remote:        raise child_exception_type(errno_num, err_msg, err_filename)        
remote:        FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'        
remote:                
remote:        During handling of the above exception, another exception occurred:        
remote:                
remote:        Traceback (most recent call last):        
remote:        File "/tmp/pip-build-5t5vcd8y/llvmlite/ffi/build.py", line 191, in <module>        
remote:        main()        
remote:        File "/tmp/pip-build-5t5vcd8y/llvmlite/ffi/build.py", line 181, in main        
remote:        main_posix('linux', '.so')        
remote:        File "/tmp/pip-build-5t5vcd8y/llvmlite/ffi/build.py", line 108, in main_posix        
remote:        "to the path for llvm-config" % (llvm_config,))        
remote:        RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config        
remote:        error: command '/app/.heroku/python/bin/python' failed with exit status 1        
remote:                
remote: ----------------------------------------        
remote:        Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5t5vcd8y/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vwkrb34r-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5t5vcd8y/llvmlite/        
To ********************************/GIT/dash-datashader
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '********************************/GIT/dash-datashader'

Exited with code exit status 1
CircleCI received exit code 1
```

Moreover, the app correctly deploys on playground. Could this problem be due to the `pip` version being updated on playground but not on gallery? Or maybe is it a problem inherent to llvm/datashader?

cc: @gzork

**Comment by gzork** [comment]
@xhlulu The deploiment fails on the Gallery, correct ? Gallery is still on 4.0 where Playground is on the latest unstable release (closer to what we'll ship in 4.1) which has the newer version of pip, unlike the Gallery.
