### ISSUE TITLE
AttributeError: 'Flask' object has no attribute 'before_first_request'

### ISSUE THREAD

**Issue by schwabts** [plotly/dash-sample-apps#788]
Hi All, the error is obviously related to Flask rather than the sample apps but the stack trace at the bottom shows the exception is raised in `dash.py` and I got it after executing
```
...\dash-clinical-analytics>python -m venv .venv
...\dash-clinical-analytics>.venv\Scripts\activate
(.venv) ...\dash-clinical-analytics>pip install -r requirements.txt
```
in an up-to-date working copy of the Dash sample app [dash-clinical-analytics/](https://github.com/plotly/dash-sample-apps/tree/main/apps/dash-clinical-analytics).

The `pip install` command finished with
```
Successfully installed Flask-2.3.2 Jinja2-3.1.2 MarkupSafe-2.1.2 Werkzeug-2.3.4 async-generator-1.10 attrs-23.1.0 beautifulsoup4-4.12.2 blinker-1.6.2 brotli-1.0.9 certifi-2023.5.7 cffi-1.15.1 charset-normalizer-3.1.0 click-8.1.3 colorama-0.4.6 dash-1.0.0 dash-core-components-1.0.0 dash-html-components-1.0.0 dash-renderer-1.0.0 dash-table-4.0.0 datetime-4.3 exceptiongroup-1.1.1 flask-compress-1.13 gunicorn-20.1.0 h11-0.14.0 idna-3.4 importlib-metadata-6.6.0 iniconfig-2.0.0 itsdangerous-2.1.2 lxml-4.9.2 numpy-1.24.3 outcome-1.2.0 packaging-23.1 pandas-2.0.1 pathlib-1.0.1 percy-2.0.2 plotly-5.14.1 pluggy-1.0.0 pycparser-2.21 pysocks-1.7.1 pytest-7.3.1 pytest-mock-3.10.0 pytest-sugar-0.9.7 python-dateutil-2.8.2 pytz-2023.3 requests-2.31.0 selenium-4.9.1 six-1.16.0 sniffio-1.3.0 sortedcontainers-2.4.0 soupsieve-2.4.1 tenacity-8.2.2 termcolor-2.3.0 tomli-2.0.1 trio-0.22.0 trio-websocket-0.10.2 tzdata-2023.3 urllib3-2.0.2 waitress-2.1.2 wsproto-1.2.0 zipp-3.15.0 zope.interface-6.0
```

so I continued doing

```
...\dash-clinical-analytics>call .venv\Scripts\activate
(.venv) ...\dash-clinical-analytics>python app.py
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    app = dash.Dash(
  File "...\dash-clinical-analytics\.venv\lib\site-packages\dash\dash.py", line 337, in __init__
    self.init_app()
  File "...\dash-clinical-analytics\.venv\lib\site-packages\dash\dash.py", line 376, in init_app
    self.server.before_first_request(self._setup_server)
AttributeError: 'Flask' object has no attribute 'before_first_request'
```

I found the closed issue [AttributeError: type object 'Flask' has no attribute 'before_first_request' with Flask > 2.2.4](https://github.com/DataDog/dd-trace-py/issues/5671) but seem to be unable to derive any way for getting the [dash-clinical-analytics](https://github.com/plotly/dash-sample-apps/tree/main/apps/dash-clinical-analytics) sample app to run.

Any help is greatly appreciated, thanks!

I'm on Windows 10 using Python 3.8.8

**Comment by SamDean332** [comment]
I was able to work around this by setting `Flask==2.1.3` in requirements

**Comment by schwabts** [comment]
> I was able to work around this by setting `Flask==2.1.3` in requirements

That worked for me, too. Thank you so much!
