### ISSUE TITLE
dash-lyft-explorer example does not work after following README instructions (installed incompatible versions)

### ISSUE THREAD

**Issue by suntzuisafterU** [plotly/dash-sample-apps#790]
# App name
dash-lyft-explorer example

# Description of bug
Followed readme (conda env + pip for requirements), crashed with:
```
[2024-01-01 08:37:22 -0600] [64238] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aaron/Documents/workspace/NEW_DIBS/dash-sample-apps/apps/dash-lyft-explorer/app.py", line 231, in <module>
    dbc.FormGroup(
  File "/home/aaron/anaconda3/envs/dash-lyft-explorer/lib/python3.7/site-packages/dash_bootstrap_components/__init__.py", line 51, in __getattr__
    f"{name} was deprecated in dash-bootstrap-components version "
AttributeError: FormGroup was deprecated in dash-bootstrap-components version 1.0.0. You are using 1.5.0. For more details please see the migration guide: https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/
[2024-01-01 08:37:22 -0600] [64238] [INFO] Worker exiting (pid: 64238)
Done reverse indexing in 0.0 seconds.

```

See error message complaining about incompatible versions.

# How to replicate the bug
Follow README.md instructions for example app.

# Other notes

**Comment by javierpastorfernandez** [comment]
Hi, I am a simply user of Dash. I just downloaded the sample and had the same problem as you had.
The problem seems to be due to an upgraded version on dash-bootstrap-components which has some incompatibilities with the version originally used for building the package. By executing this command it should be solved
``pip install "dash-bootstrap-components<1
